# -*- coding: utf-8 -*-
"""By their Network You Shall Know Financial Crime: Detecting Illegal Corporate Service Providers Through Relational Network Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EqvR3QfrVFqWiDO1ONrUfCZwJyix9_ro

# By their Network You Shall Know Financial Crime: Detecting Illegal Corporate Service Providers Through Relational Network Learning

## Libraries
"""

import argparse
import time

import os

os.environ["DGLBACKEND"] = "pytorch"
import dgl
import dgl.data
import torch as th
import torch.nn as nn
import torch.nn.functional as F

import pandas as pd
import numpy as np
import networkx as nx
from sklearn.preprocessing import LabelEncoder

from sklearn.manifold import TSNE
import umap

from collections import defaultdict


import dgl.function as fn
import dgl.nn as dglnn


import tqdm

from sklearn.metrics import f1_score, balanced_accuracy_score

import matplotlib.pyplot as plt
import matplotlib as mpl

from sklearn.metrics import precision_score, recall_score, roc_auc_score
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

"""## Data Preparetion,  Data Cleaning and Data Merging"""

#### Loading Data Directors ####

df_directors = pd.read_csv("C:/Users/df_directors.tsv", sep='\t')
df_directors.shape

#### Loading Data Owners ####

df_owners = pd.read_csv("C:/Users/df_owners.tsv", sep='\t')
df_owners = df_owners.dropna() # Only one company
df_owners.shape

#### Loading Data Address ####

df_address = pd.read_csv("C:/Users/df_address.tsv", sep='\t')
df_address.shape

#### Loading Data Companies ####

df_c = pd.read_csv("C:/Users/df_c.tsv", sep='\t')
df_c.shape

df_c['legal_form'] = df_c['legal_form'].fillna('Not Available')

#### Loading CSP Data ####

df_licensed_csp_positive_examples = pd.read_csv("C:/Users/final_df_licensed_csp_positive_examples.tsv", sep='\t')
csp_directors = set(df_licensed_csp_positive_examples['dir_id'])
csp_directors

#### Loading NON_CSP DATA ####

df_directors_no_csp_negative_examples = pd.read_csv("C:/Users/andre/OneDrive/Desktop/Tesi di Laurea/Dati/created by me/final_df_directors_no_csp_negative_examples.tsv", sep='\t')
non_csp_directors = set(df_directors_no_csp_negative_examples['dir_id'])
non_csp_directors

#### Labelling Function on filtered dataset ####

#CSP = 1
#Not-CSP = 0
#Unlabelled = -1

def assign_label(dir_id):
    if dir_id in csp_directors:
        return 1
    elif dir_id in non_csp_directors:
        return 0
    else:
        return -1

df_directors['labels'] = df_directors['dir_id'].apply(assign_label)

#### Original Directors Keys ####

df_directors_keys = pd.read_csv("C:/Users//df_directors_keys.tsv", sep="\t")
df_directors_keys.shape

#### Original Companies Keys ####

df_c_keys = pd.read_csv("C:/Users/df_c_keys.tsv", sep="\t")
df_c_keys.shape

#### Additional Dataset ####

df_cluster_20201013 = pd.read_csv("C:/Users/df_cluster_20201013.csv")
df_cluster_20201013.shape

#### Adding dir_id_key from df_directors_keys dataset to df_cluster_20201013 dataset ####

df_director_keys_unique = df_directors_keys.drop_duplicates(subset="dir_id")

df_cluster_20201013 = pd.merge(
    df_cluster_20201013,
    df_director_keys_unique[["dir_id", "dir_id_key"]],
    on="dir_id",
    how="left")

df_cluster_20201013.shape

#### df_directors_filtered dataset (final df_directors dataset) ####

df_directors_filtered = df_directors[df_directors["dir_id"].isin(df_cluster_20201013["dir_id_key"])]
df_directors_filtered.shape

count_0 = df_directors_filtered[df_directors_filtered['labels'] == 0].shape[0]
count_1 = df_directors_filtered[df_directors_filtered['labels'] == 1].shape[0]
count_neg_1 = df_directors_filtered[df_directors_filtered['labels'] == -1].shape[0]

print("Number of NOT CSP rows ('labels' = 0):", count_0)
print("Number of CSP rows ('labels' = 1):", count_1)
print("Number of Unlabelled rows ('labels' = -1):", count_neg_1)

df_filtered_zero = df_directors_filtered[df_directors_filtered['labels']==0]
unique_ids_count_zero = df_filtered_zero.groupby('dir_id').nunique()
df_filtered_one = df_directors_filtered[df_directors_filtered['labels']==1]
unique_ids_count_one = df_filtered_one.groupby('dir_id').nunique()
df_filtered_unlab = df_directors_filtered[df_directors_filtered['labels']==-1]
unique_ids_count_unlab = df_filtered_unlab.groupby('dir_id').nunique()

print("Number of unique NOT CSP dir_ids ('labels' = 0):", unique_ids_count_zero.shape[0])
print("Number of unique CSP dir_ids ('labels' = 1):", unique_ids_count_one.shape[0])
print("Number of unique Unlabelled dir_ids ('labels' = -1):", unique_ids_count_unlab.shape[0])

#### Starting Merging Phase ####

df_all = pd.merge(df_directors_filtered, df_owners, on= 'bvd_id')
df_all.shape

#### Merging Phase ####

df_all = pd.merge(df_all, df_address, on= 'bvd_id')
df_all.shape

#### Merging Phase ####

df_all = pd.merge(df_all, df_c, on= 'bvd_id')
df_all.shape

"""## Label Encoding & Mapping (DGL)"""

#### Label Encoding for Directors, Companies, Owners and Address (DGL needs sequential numbers to construct graph) ####

director_encoder = LabelEncoder()
df_all['new_dir_id'] = director_encoder.fit_transform(df_all['dir_id'])

company_encoder = LabelEncoder()
df_all['new_bvd_id'] = company_encoder.fit_transform(df_all['bvd_id'])

#Owner Encoder potrebbe esser problematico perchè non so se codificare gli owner come compagnie o con id_diversi.
owner_encoder = LabelEncoder()
df_all['new_guo_id'] = owner_encoder.fit_transform(df_all['guo_id'])

address_encoder = LabelEncoder()
df_all['new_address_combined_gr'] = address_encoder.fit_transform(df_all['address_combined_gr'])

df_all.shape

#### Directors, Companies, Addresses and Owners Mapping ####

#Directors Map
dir_mapping = df_all[['new_dir_id', 'dir_id']].drop_duplicates().set_index('new_dir_id')['dir_id'].to_dict()

#Companies Map
bvd_mapping = df_all[['new_bvd_id', 'bvd_id']].drop_duplicates().set_index('new_bvd_id')['bvd_id'].to_dict()

#Owner Map
guo_mapping = df_all[['new_guo_id', 'guo_id']].drop_duplicates().set_index('new_guo_id')['guo_id'].to_dict()

#Address_combined_gr Map
address_combined_gr_mapping = df_all[['new_address_combined_gr', 'address_combined_gr']].drop_duplicates().set_index('new_address_combined_gr')['address_combined_gr'].to_dict()

"""## Heterogeneus Network (DGL)"""

#### Creating Relations between new directors and new companies ids ####

director_to_company_edges = set()

for idx, row in df_all.iterrows():
    director_node = int(row['new_dir_id'])
    company_node = int(row['new_bvd_id'])
    director_to_company_edges.add((director_node, company_node))


director_to_company_edges = list(director_to_company_edges)
director_to_company_edges

#### Creating Relations between new companies and new owners ids ####

company_to_owner_edges = set()

for idx, row in df_all.iterrows():
    company_node = int(row['new_bvd_id'])
    owner_node = int(row['new_guo_id'])
    company_to_owner_edges.add((company_node,owner_node))


company_to_owner_edges = list(company_to_owner_edges)
company_to_owner_edges

#### Creating Relations between new companies and new address ids ####

company_to_address_edges = set()

for idx, row in df_all.iterrows():
    company_node = int(row['new_bvd_id'])
    address_node = int(row['new_address_combined_gr'])
    company_to_address_edges.add((company_node, address_node))


company_to_address_edges = list(company_to_address_edges)
company_to_address_edges

#### Creating Nodes Directors/Companies ####

director_nodes, company_nodes = zip(*director_to_company_edges)
director_nodes_tensor = th.tensor(director_nodes, dtype=th.int64)
company_nodes_tensor = th.tensor(company_nodes, dtype=th.int64)

#### Creating Nodes Companies/Owners ####

company_nodes_owner, owner_nodes = zip(*company_to_owner_edges)
company_nodes_owner_tensor = th.tensor(company_nodes_owner, dtype=th.int64)
owner_nodes_tensor = th.tensor(owner_nodes, dtype=th.int64)

#### Creating Nodes Companies/Address ####

company_nodes_address, address_nodes = zip(*company_to_address_edges)
company_nodes_address_tensor = th.tensor(company_nodes_address, dtype=th.int64)
address_nodes_tensor = th.tensor(address_nodes, dtype=th.int64)

#### Heterogeneus Complex Graph DGL ####

graph_data = {
    ('director', 'works_for', 'company'): (director_nodes_tensor, company_nodes_tensor),
    ('company', 'directed_by', 'director'): (company_nodes_tensor, director_nodes_tensor),
    ('company', 'owned_by', 'owner'): (company_nodes_owner_tensor, owner_nodes_tensor),
    ('owner', 'owns', 'company'): (owner_nodes_tensor, company_nodes_owner_tensor),
    ('company', 'located_at', 'address'): (company_nodes_address_tensor, address_nodes_tensor),
    ('address', 'location_of', 'company'): (address_nodes_tensor, company_nodes_address_tensor)
}

g = dgl.heterograph(graph_data)
g

"""## Network's Initialization (Nodes' IDs)"""

######### Node's '_ID' Features #######
# Feature "_ID" for directors, companies, addesses and owners: "_ID" has a unique id for every node in the Heterogeneous Graph #

num_directors = g.number_of_nodes('director')
num_companies = g.number_of_nodes('company')
num_owners = g.number_of_nodes('owner')
num_addresses = g.number_of_nodes('address')

total_nodes = num_directors + num_companies + num_owners + num_addresses

all_ids = th.randperm(total_nodes)

director_ids = all_ids[:num_directors]
company_ids = all_ids[num_directors:num_directors + num_companies]
owner_ids = all_ids[num_directors + num_companies:num_directors + num_companies + num_owners]
address_ids = all_ids[num_directors + num_companies + num_owners:]

g.nodes['director'].data['_ID'] = director_ids
g.nodes['company'].data['_ID'] = company_ids
g.nodes['owner'].data['_ID'] = owner_ids
g.nodes['address'].data['_ID'] = address_ids

"""## Network's Initialization (Edge's IDs)"""

###### Edge's '_ID' Features #######
# Feature "_ID" for every edge: every relation has a unique id #

num_edges_director_company = g.number_of_edges(('director', 'works_for', 'company'))
num_edges_company_director = g.number_of_edges(('company', 'directed_by', 'director'))
num_edges_company_owner = g.number_of_edges(('company', 'owned_by', 'owner'))
num_edges_owner_company = g.number_of_edges(('owner', 'owns', 'company'))
num_edges_company_address = g.number_of_edges(('company', 'located_at', 'address'))
num_edges_address_company = g.number_of_edges(('address', 'location_of', 'company'))

total_edges = (num_edges_director_company + num_edges_company_director +
               num_edges_company_owner + num_edges_owner_company +
               num_edges_company_address + num_edges_address_company)

all_edge_ids = th.randperm(total_edges)

edge_ids_director_company = all_edge_ids[:num_edges_director_company]
edge_ids_company_director = all_edge_ids[num_edges_director_company:num_edges_director_company + num_edges_company_director]
edge_ids_company_owner = all_edge_ids[num_edges_director_company + num_edges_company_director:num_edges_director_company + num_edges_company_director + num_edges_company_owner]
edge_ids_owner_company = all_edge_ids[num_edges_director_company + num_edges_company_director + num_edges_company_owner:num_edges_director_company + num_edges_company_director + num_edges_company_owner + num_edges_owner_company]
edge_ids_company_address = all_edge_ids[num_edges_director_company + num_edges_company_director + num_edges_company_owner + num_edges_owner_company:num_edges_director_company + num_edges_company_director + num_edges_company_owner + num_edges_owner_company + num_edges_company_address]
edge_ids_address_company = all_edge_ids[num_edges_director_company + num_edges_company_director + num_edges_company_owner + num_edges_owner_company + num_edges_company_address:]

g.edges['director', 'works_for', 'company'].data['_ID'] = edge_ids_director_company
g.edges['company', 'directed_by', 'director'].data['_ID'] = edge_ids_company_director
g.edges['company', 'owned_by', 'owner'].data['_ID'] = edge_ids_company_owner
g.edges['owner', 'owns', 'company'].data['_ID'] = edge_ids_owner_company
g.edges['company', 'located_at', 'address'].data['_ID'] = edge_ids_company_address
g.edges['address', 'location_of', 'company'].data['_ID'] = edge_ids_address_company

"""## Directors Node Labelling"""

df_directors_unique = df_all.drop_duplicates(subset='new_dir_id')
df_directors_unique = df_directors_unique.sort_values(by='new_dir_id')
labels = th.tensor(df_directors_unique['labels'].values)
g.nodes['director'].data['labels'] = labels
g.nodes['director'].data['label'] = labels

"""## Nodes Splitting (MASKS)"""

directors_with_label_0 = df_all[df_all['labels'] == 0]['new_dir_id'].unique()
directors_with_label_1 = df_all[df_all['labels'] == 1]['new_dir_id'].unique()

num_directors = max(director_nodes) + 1
train_mask = th.zeros(num_directors, dtype=th.bool)
val_mask = th.zeros(num_directors, dtype=th.bool)
test_mask = th.zeros(num_directors, dtype=th.bool)

#### Masks' size ####

train_size = 0.7
val_size = 0.15
test_size = 1 - train_size - val_size

def split_indices(indices, train_size, val_size, test_size):

    np.random.shuffle(indices)
    n = len(indices)
    n_train = int(n * train_size)
    n_val = int(n * val_size)

    train_indices = indices[:n_train]
    val_indices = indices[n_train:n_train + n_val]
    test_indices = indices[n_train + n_val:]

    return train_indices, val_indices, test_indices

directors_with_label_0 = np.array(list(directors_with_label_0))
directors_with_label_1 = np.array(list(directors_with_label_1))

non_csp_train, non_csp_val, non_csp_test = split_indices(directors_with_label_0, train_size, val_size, test_size)
csp_train, csp_val, csp_test = split_indices(directors_with_label_1, train_size, val_size, test_size)

train_mask[th.tensor(np.concatenate((csp_train, non_csp_train)), dtype=th.int64)] = True
val_mask[th.tensor(np.concatenate((csp_val, non_csp_val)), dtype=th.int64)] = True
test_mask[th.tensor(np.concatenate((csp_test, non_csp_test)), dtype=th.int64)] = True

### Masks Features ####

g.nodes['director'].data['train_mask'] = train_mask
g.nodes['director'].data['val_mask'] = val_mask
g.nodes['director'].data['test_mask'] = test_mask

# Another Mask feature with unlabelled director nodes #

directors_with_label_minus_1 = df_all[df_all['labels'] == -1]['new_dir_id'].unique()
minus_1_mask = th.zeros(num_directors, dtype=th.bool)

for idx in directors_with_label_minus_1:
    minus_1_mask[idx] = True
g.nodes['director'].data['no_labelled_test_mask'] = minus_1_mask

g.nodes['director'].data['train_mask'] = g.nodes['director'].data['train_mask'].int()
g.nodes['director'].data['train_mask'] = g.nodes['director'].data['train_mask'].type(th.uint8)
g.nodes['director'].data['train_mask']

g.nodes['director'].data['val_mask'] = g.nodes['director'].data['val_mask'].int()
g.nodes['director'].data['val_mask'] = g.nodes['director'].data['val_mask'].type(th.uint8)
g.nodes['director'].data['val_mask']

g.nodes['director'].data['test_mask'] = g.nodes['director'].data['test_mask'].int()
g.nodes['director'].data['test_mask'] = g.nodes['director'].data['test_mask'].type(th.uint8)
g.nodes['director'].data['test_mask']

g.nodes['director'].data['no_labelled_test_mask'] = g.nodes['director'].data['no_labelled_test_mask'].int()
g.nodes['director'].data['no_labelled_test_mask'] = g.nodes['director'].data['no_labelled_test_mask'].type(th.uint8)
g.nodes['director'].data['no_labelled_test_mask']

train_tensor = g.nodes['director'].data['train_mask']
train_ind = (train_tensor == 1).nonzero(as_tuple=True)[0]

train_ind_list = train_ind.tolist()

print(train_ind_list)

valid_tensor = g.nodes['director'].data['val_mask']
valid_ind = (valid_tensor == 1).nonzero(as_tuple=True)[0]

valid_ind_list = valid_ind.tolist()

print(valid_ind_list)

test_tensor = g.nodes['director'].data['test_mask']
test_ind = (test_tensor == 1).nonzero(as_tuple=True)[0]

test_ind_list = test_ind.tolist()

print(test_ind_list)

unlab_tensor = g.nodes['director'].data['no_labelled_test_mask']
unlab_ind = (unlab_tensor == 1).nonzero(as_tuple=True)[0]

unlab_ind_list = unlab_ind.tolist()

print(unlab_ind_list)

#### Mapping Dataset Directors Unlabeled ####

new_dir_ids = []
dir_ids = []
for new_dir_id in unlab_ind_list:
    if new_dir_id in dir_mapping:
        new_dir_ids.append(new_dir_id)
        dir_ids.append(dir_mapping[new_dir_id])

df_idx_unlab = pd.DataFrame({'new_dir_id': new_dir_ids, 'dir_id': dir_ids})

df_idx_unlab

"""## GNNs Functions"""

"""RGCN layer implementation"""


class RelGraphConvLayer(nn.Module):
    r"""Relational graph convolution layer.

    Parameters
    ----------
    in_feat : int
        Input feature size.
    out_feat : int
        Output feature size.
    rel_names : list[str]
        Relation names.
    num_bases : int, optional
        Number of bases. If is none, use number of relations. Default: None.
    weight : bool, optional
        True if a linear layer is applied after message passing. Default: True
    bias : bool, optional
        True if bias is added. Default: True
    activation : callable, optional
        Activation function. Default: None
    self_loop : bool, optional
        True to include self loop message. Default: False
    dropout : float, optional
        Dropout rate. Default: 0.0
    """

    def __init__(
        self,
        in_feat,
        out_feat,
        rel_names,
        num_bases,
        *,
        weight=True,
        bias=True,
        activation=None,
        self_loop=False,
        dropout=0.0
    ):
        super(RelGraphConvLayer, self).__init__()
        self.in_feat = in_feat
        self.out_feat = out_feat
        self.rel_names = rel_names
        self.num_bases = num_bases
        self.bias = bias
        self.activation = activation
        self.self_loop = self_loop

        self.conv = dglnn.HeteroGraphConv(
            {
                rel: dglnn.GraphConv(
                    in_feat, out_feat, norm="right", weight=False, bias=False
                )
                for rel in rel_names
            }
        )

        self.use_weight = weight
        self.use_basis = num_bases < len(self.rel_names) and weight
        if self.use_weight:
            if self.use_basis:
                self.basis = dglnn.WeightBasis(
                    (in_feat, out_feat), num_bases, len(self.rel_names)
                )
            else:
                self.weight = nn.Parameter(
                    th.Tensor(len(self.rel_names), in_feat, out_feat)
                )
                nn.init.xavier_uniform_(
                    self.weight, gain=nn.init.calculate_gain("relu")
                )

        # bias
        if bias:
            self.h_bias = nn.Parameter(th.Tensor(out_feat))
            nn.init.zeros_(self.h_bias)

        # weight for self loop
        if self.self_loop:
            self.loop_weight = nn.Parameter(th.Tensor(in_feat, out_feat))
            nn.init.xavier_uniform_(
                self.loop_weight, gain=nn.init.calculate_gain("relu")
            )

        self.dropout = nn.Dropout(dropout)

    def forward(self, g, inputs):
        """Forward computation

        Parameters
        ----------
        g : DGLGraph
            Input graph.
        inputs : dict[str, torch.Tensor]
            Node feature for each node type.

        Returns
        -------
        dict[str, torch.Tensor]
            New node features for each node type.
        """
        g = g.local_var()
        if self.use_weight:
            weight = self.basis() if self.use_basis else self.weight
            wdict = {
                self.rel_names[i]: {"weight": w.squeeze(0)}
                for i, w in enumerate(th.split(weight, 1, dim=0))
            }
        else:
            wdict = {}

        if g.is_block:
            inputs_src = inputs
            inputs_dst = {
                k: v[: g.number_of_dst_nodes(k)] for k, v in inputs.items()
            }
        else:
            inputs_src = inputs_dst = inputs

        hs = self.conv(g, inputs, mod_kwargs=wdict)

        def _apply(ntype, h):
            if self.self_loop:
                h = h + th.matmul(inputs_dst[ntype], self.loop_weight)
            if self.bias:
                h = h + self.h_bias
            if self.activation:
                h = self.activation(h)
            return self.dropout(h)

        return {ntype: _apply(ntype, h) for ntype, h in hs.items()}


class RelGraphConvLayerHeteroAPI(nn.Module):
    r"""Relational graph convolution layer.

    Parameters
    ----------
    in_feat : int
        Input feature size.
    out_feat : int
        Output feature size.
    rel_names : list[str]
        Relation names.
    num_bases : int, optional
        Number of bases. If is none, use number of relations. Default: None.
    weight : bool, optional
        True if a linear layer is applied after message passing. Default: True
    bias : bool, optional
        True if bias is added. Default: True
    activation : callable, optional
        Activation function. Default: None
    self_loop : bool, optional
        True to include self loop message. Default: False
    dropout : float, optional
        Dropout rate. Default: 0.0
    """

    def __init__(
        self,
        in_feat,
        out_feat,
        rel_names,
        num_bases,
        *,
        weight=True,
        bias=True,
        activation=None,
        self_loop=False,
        dropout=0.0
    ):
        super(RelGraphConvLayerHeteroAPI, self).__init__()
        self.in_feat = in_feat
        self.out_feat = out_feat
        self.rel_names = rel_names
        self.num_bases = num_bases
        self.bias = bias
        self.activation = activation
        self.self_loop = self_loop

        self.use_weight = weight
        self.use_basis = num_bases < len(self.rel_names) and weight
        if self.use_weight:
            if self.use_basis:
                self.basis = dglnn.WeightBasis(
                    (in_feat, out_feat), num_bases, len(self.rel_names)
                )
            else:
                self.weight = nn.Parameter(
                    th.Tensor(len(self.rel_names), in_feat, out_feat)
                )
                nn.init.xavier_uniform_(
                    self.weight, gain=nn.init.calculate_gain("relu")
                )

        # bias
        if bias:
            self.h_bias = nn.Parameter(th.Tensor(out_feat))
            nn.init.zeros_(self.h_bias)

        # weight for self loop
        if self.self_loop:
            self.loop_weight = nn.Parameter(th.Tensor(in_feat, out_feat))
            nn.init.xavier_uniform_(
                self.loop_weight, gain=nn.init.calculate_gain("relu")
            )

        self.dropout = nn.Dropout(dropout)

    def forward(self, g, inputs):
        """Forward computation

        Parameters
        ----------
        g : DGLGraph
            Input graph.
        inputs : dict[str, torch.Tensor]
            Node feature for each node type.

        Returns
        -------
        dict[str, torch.Tensor]
            New node features for each node type.
        """
        g = g.local_var()
        if self.use_weight:
            weight = self.basis() if self.use_basis else self.weight
            wdict = {
                self.rel_names[i]: {"weight": w.squeeze(0)}
                for i, w in enumerate(th.split(weight, 1, dim=0))
            }
        else:
            wdict = {}

        inputs_src = inputs_dst = inputs

        for srctype, _, _ in g.canonical_etypes:
            g.nodes[srctype].data["h"] = inputs[srctype]

        if self.use_weight:
            g.apply_edges(fn.copy_u("h", "m"))
            m = g.edata["m"]
            for rel in g.canonical_etypes:
                _, etype, _ = rel
                g.edges[rel].data["h*w_r"] = th.matmul(
                    m[rel], wdict[etype]["weight"]
                )
        else:
            g.apply_edges(fn.copy_u("h", "h*w_r"))

        g.update_all(fn.copy_e("h*w_r", "m"), fn.sum("m", "h"))

        def _apply(ntype):
            h = g.nodes[ntype].data["h"]
            if self.self_loop:
                h = h + th.matmul(inputs_dst[ntype], self.loop_weight)
            if self.bias:
                h = h + self.h_bias
            if self.activation:
                h = self.activation(h)
            return self.dropout(h)

        return {ntype: _apply(ntype) for ntype in g.dsttypes}


class RelGraphEmbed(nn.Module):
    r"""Embedding layer for featureless heterograph."""

    def __init__(
        self, g, embed_size, embed_name="embed", activation=None, dropout=0.0
    ):
        super(RelGraphEmbed, self).__init__()
        self.g = g
        self.embed_size = embed_size
        self.embed_name = embed_name
        self.activation = activation
        self.dropout = nn.Dropout(dropout)

        # create weight embeddings for each node for each relation
        self.embeds = nn.ParameterDict()
        for ntype in g.ntypes:
            embed = nn.Parameter(th.Tensor(g.num_nodes(ntype), self.embed_size))
            nn.init.xavier_uniform_(embed, gain=nn.init.calculate_gain("relu"))
            self.embeds[ntype] = embed

    def forward(self, block=None):
        """Forward computation

        Parameters
        ----------
        block : DGLGraph, optional
            If not specified, directly return the full graph with embeddings stored in
            :attr:`embed_name`. Otherwise, extract and store the embeddings to the block
            graph and return.

        Returns
        -------
        DGLGraph
            The block graph fed with embeddings.
        """
        return self.embeds


class EntityClassify(nn.Module):
    def __init__(
        self,
        g,
        h_dim,
        out_dim,
        num_bases,
        num_hidden_layers=1,
        dropout=0,
        use_self_loop=False,
    ):
        super(EntityClassify, self).__init__()
        self.g = g
        self.h_dim = h_dim
        self.out_dim = out_dim
        self.rel_names = list(set(g.etypes))
        self.rel_names.sort()
        if num_bases < 0 or num_bases > len(self.rel_names):
            self.num_bases = len(self.rel_names)
        else:
            self.num_bases = num_bases
        self.num_hidden_layers = num_hidden_layers
        self.dropout = dropout
        self.use_self_loop = use_self_loop

        self.embed_layer = RelGraphEmbed(g, self.h_dim)
        self.layers = nn.ModuleList()
        # i2h
        self.layers.append(
            RelGraphConvLayer(
                self.h_dim,
                self.h_dim,
                self.rel_names,
                self.num_bases,
                activation=F.relu,
                self_loop=self.use_self_loop,
                dropout=self.dropout,
                weight=False,
            )
        )
        # h2h
        for i in range(self.num_hidden_layers):
            self.layers.append(
                RelGraphConvLayer(
                    self.h_dim,
                    self.h_dim,
                    self.rel_names,
                    self.num_bases,
                    activation=F.relu,
                    self_loop=self.use_self_loop,
                    dropout=self.dropout,
                )
            )
        # h2o
        self.layers.append(
            RelGraphConvLayer(
                self.h_dim,
                self.out_dim,
                self.rel_names,
                self.num_bases,
                activation=None,
                self_loop=self.use_self_loop,
            )
        )

    def forward(self, h=None, blocks=None):
        if h is None:
            # full graph training
            h = self.embed_layer()
        if blocks is None:
            # full graph training
            for layer in self.layers:
                h = layer(self.g, h)
        else:
            # minibatch training
            for layer, block in zip(self.layers, blocks):
                h = layer(block, h)
        return h

    def inference(self, g, batch_size, device, num_workers, x=None):
        """Minibatch inference of final representation over all node types.

        ***NOTE***
        For node classification, the model is trained to predict on only one node type's
        label.  Therefore, only that type's final representation is meaningful.
        """

        if x is None:
            x = self.embed_layer()

        for l, layer in enumerate(self.layers):
            y = {
                k: th.zeros(
                    g.num_nodes(k),
                    self.h_dim if l != len(self.layers) - 1 else self.out_dim,
                )
                for k in g.ntypes
            }

            sampler = dgl.dataloading.MultiLayerFullNeighborSampler(1)
            dataloader = dgl.dataloading.DataLoader(
                g,
                {k: th.arange(g.num_nodes(k)) for k in g.ntypes},
                sampler,
                batch_size=batch_size,
                shuffle=True,
                drop_last=False,
                num_workers=num_workers,
            )

            with dataloader.enable_cpu_affinity():
                for input_nodes, output_nodes, blocks in tqdm.tqdm(dataloader):
                    block = blocks[0].to(device)

                    h = {
                        k: x[k][input_nodes[k]].to(device)
                        for k in input_nodes.keys()
                    }
                    h = layer(block, h)

                    for k in output_nodes.keys():
                        y[k][output_nodes[k]] = h[k].cpu()

            x = y
        return y


class EntityClassify_HeteroAPI(nn.Module):
    def __init__(
        self,
        g,
        h_dim,
        out_dim,
        num_bases,
        num_hidden_layers=1,
        dropout=0,
        use_self_loop=False,
    ):
        super(EntityClassify_HeteroAPI, self).__init__()
        self.g = g
        self.h_dim = h_dim
        self.out_dim = out_dim
        self.rel_names = list(set(g.etypes))
        self.rel_names.sort()
        if num_bases < 0 or num_bases > len(self.rel_names):
            self.num_bases = len(self.rel_names)
        else:
            self.num_bases = num_bases
        self.num_hidden_layers = num_hidden_layers
        self.dropout = dropout
        self.use_self_loop = use_self_loop

        self.embed_layer = RelGraphEmbed(g, self.h_dim)
        self.layers = nn.ModuleList()
        # i2h
        self.layers.append(
            RelGraphConvLayerHeteroAPI(
                self.h_dim,
                self.h_dim,
                self.rel_names,
                self.num_bases,
                activation=F.relu,
                self_loop=self.use_self_loop,
                dropout=self.dropout,
                weight=False,
            )
        )
        # h2h
        for i in range(self.num_hidden_layers):
            self.layers.append(
                RelGraphConvLayerHeteroAPI(
                    self.h_dim,
                    self.h_dim,
                    self.rel_names,
                    self.num_bases,
                    activation=F.relu,
                    self_loop=self.use_self_loop,
                    dropout=self.dropout,
                )
            )
        # h2o
        self.layers.append(
            RelGraphConvLayerHeteroAPI(
                self.h_dim,
                self.out_dim,
                self.rel_names,
                self.num_bases,
                activation=None,
                self_loop=self.use_self_loop,
            )
        )

    def forward(self, h=None, blocks=None):
        if h is None:
            # full graph training
            h = self.embed_layer()
        if blocks is None:
            # full graph training
            for layer in self.layers:
                h = layer(self.g, h)
        else:
            # minibatch training
            for layer, block in zip(self.layers, blocks):
                h = layer(block, h)
        return h

    def inference(self, g, batch_size, device, num_workers, x=None):
        """Minibatch inference of final representation over all node types.

        ***NOTE***
        For node classification, the model is trained to predict on only one node type's
        label.  Therefore, only that type's final representation is meaningful.
        """

        if x is None:
            x = self.embed_layer()

        for l, layer in enumerate(self.layers):
            y = {
                k: th.zeros(
                    g.num_nodes(k),
                    self.h_dim if l != len(self.layers) - 1 else self.out_dim,
                )
                for k in g.ntypes
            }

            sampler = dgl.dataloading.MultiLayerFullNeighborSampler(1)
            dataloader = dgl.dataloading.DataLoader(
                g,
                {k: th.arange(g.num_nodes(k)) for k in g.ntypes},
                sampler,
                batch_size=batch_size,
                shuffle=True,
                drop_last=False,
                num_workers=num_workers,
            )

            for input_nodes, output_nodes, blocks in tqdm.tqdm(dataloader):
                block = blocks[0].to(device)

                h = {
                    k: x[k][input_nodes[k]].to(device)
                    for k in input_nodes.keys()
                }
                h = layer(block, h)

                for k in h.keys():
                    y[k][output_nodes[k]] = h[k].cpu()

            x = y
        return y

predict_category= 'director'
category = predict_category
num_classes = 2

train_mask = g.nodes[category].data.pop("train_mask")
test_mask = g.nodes[category].data.pop("test_mask")
val_mask = g.nodes[category].data.pop("val_mask")
no_labelled_test_mask = g.nodes[category].data.pop('no_labelled_test_mask')

train_idx = th.nonzero(train_mask, as_tuple=False).squeeze()
val_idx = th.nonzero(val_mask, as_tuple=False).squeeze()
test_idx = th.nonzero(test_mask, as_tuple=False).squeeze()
no_labelled_test_idx = th.nonzero(no_labelled_test_mask, as_tuple=False).squeeze()
labels = g.nodes[category].data.pop("labels")
category_id = len(g.ntypes)
for i, ntype in enumerate(g.ntypes):
        if ntype == category:
            category_id = i

model = EntityClassify(
        g,
        16,
        num_classes,
        num_bases = 4,
        num_hidden_layers = 4,
        use_self_loop=True,
        dropout = 0.2)

model

model()

optimizer = th.optim.Adam(model.parameters(), lr = 0.001,  weight_decay = 0.01)
optimizer

#### Some useful metrics (function) for model evaluation (imbalanced task) ####

def calculate_f1_score(logits, labels):
    predictions = th.argmax(logits, dim=1)
    f1 = f1_score(labels.cpu().numpy(), predictions.cpu().numpy(), average='weighted')
    return th.tensor(f1) # Convert to a 0-dimensional tensor

def calculate_balanced_accuracy(logits, labels):
    predictions = th.argmax(logits, dim=1)
    balanced_acc = balanced_accuracy_score(labels.cpu().numpy(), predictions.cpu().numpy())
    return th.tensor(balanced_acc) # Convert to a 0-dimensional tensor

print("start training...")

import numpy as np

dur = []
train_loss_history = []
train_BAC_history = []
train_F1_history = []
train_acc_history = []

val_loss_history = []
val_BAC_history = []
val_F1_history = []
val_acc_history = []

n_epochs = 40

model.train()

# Early Stopping
best_val_loss = float('inf')
patience = 5  # =  n_epochs early stopping
consecutive_counter = 0

for epoch in range(n_epochs):
    optimizer.zero_grad()

    t0 = time.time()

    logits = model()[category]
    loss = F.cross_entropy(logits[train_idx], labels[train_idx])
    loss.backward()
    optimizer.step()
    t1 = time.time()

    dur.append(t1 - t0)

    train_acc = th.sum(
        logits[train_idx].argmax(dim=1) == labels[train_idx]
    ).item() / len(train_idx)
    train_f1 = calculate_f1_score(logits[train_idx], labels[train_idx])
    train_balanced_acc = calculate_balanced_accuracy(logits[train_idx], labels[train_idx])

    val_loss = F.cross_entropy(logits[val_idx], labels[val_idx])
    val_acc = th.sum(
        logits[val_idx].argmax(dim=1) == labels[val_idx]
    ).item() / len(val_idx)
    val_f1 = calculate_f1_score(logits[val_idx], labels[val_idx])
    val_balanced_acc = calculate_balanced_accuracy(logits[val_idx], labels[val_idx])

    train_loss_history.append(loss.item())
    val_loss_history.append(val_loss.item())

    train_BAC_history.append(train_balanced_acc.item())
    train_F1_history.append(train_f1.item())
    train_acc_history.append(train_acc)

    val_BAC_history.append(val_balanced_acc.item())
    val_F1_history.append(val_f1.item())
    val_acc_history.append(val_acc)

    if dur:
        avg_dur = np.average(dur)
    else:
        avg_dur = 0

    print(
        "Epoch {:05d} | Train Acc: {:.4f} | Train F1: {:.4f} | Train BAC: {:.4f} | "
        "Train Loss: {:.4f} | Valid Acc: {:.4f} | Valid F1: {:.4f} | Valid BAC: {:.4f} | "
        "Valid loss: {:.4f} | Time: {:.4f}".format(
            epoch,
            train_acc,
            train_f1,
            train_balanced_acc,
            loss.item(),
            val_acc,
            val_f1,
            val_balanced_acc,
            val_loss.item(),
            avg_dur,
        )
    )

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        consecutive_counter = 0
        consecutive_counter += 1

    if consecutive_counter >= patience:
        print(f"Early stopping at epoch {epoch}")
        break

print()

mpl.rcParams['font.family'] = 'serif'
mpl.rcParams['font.size'] = 11

epochs = range(1, n_epochs + 1)

fig, ax = plt.subplots(figsize=(6, 4))

ax.plot(epochs, train_loss_history, color='#2c3e50', linewidth=1.5, label='Training Loss')
ax.plot(epochs, val_loss_history, color='#c0392b', linewidth=1.5, linestyle='--', label='Validation Loss')

ax.set_title('Training and Validation Loss', fontsize=12, fontweight='bold', pad=10)
ax.set_xlabel('Epochs', fontsize=11)
ax.set_ylabel('Loss', fontsize=11)
ax.legend(fontsize=10, frameon=True, edgecolor='#cccccc', fancybox=False)

ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_linewidth(0.8)
ax.spines['bottom'].set_linewidth(0.8)
ax.tick_params(axis='both', labelsize=10, length=3)
ax.grid(False)

plt.tight_layout()
plt.savefig('loss_curve.pdf', dpi=300, bbox_inches='tight')
plt.show()

mpl.rcParams['font.family'] = 'serif'
mpl.rcParams['font.size'] = 11

max_iter = n_epochs - 1
epochs = range(1, n_epochs + 1)

fig, ax = plt.subplots(figsize=(6, 4))

ax.plot(epochs, train_BAC_history, color='#2c3e50', linewidth=1.5,
        label='Training BAC (Last = %.4f)' % train_BAC_history[max_iter])
ax.plot(epochs, val_BAC_history, color='#c0392b', linewidth=1.5, linestyle='--',
        label='Validation BAC (Last = %.4f)' % val_BAC_history[max_iter])

ax.set_title('Training and Validation BAC', fontsize=12, fontweight='bold', pad=10)
ax.set_xlabel('Epochs', fontsize=11)
ax.set_ylabel('BAC Value', fontsize=11)
ax.legend(fontsize=10, frameon=True, edgecolor='#cccccc', fancybox=False)

ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_linewidth(0.8)
ax.spines['bottom'].set_linewidth(0.8)
ax.tick_params(axis='both', labelsize=10, length=3)
ax.grid(False)

plt.tight_layout()
plt.savefig('bac_curve.pdf', dpi=300, bbox_inches='tight')
plt.show()

mpl.rcParams['font.family'] = 'serif'
mpl.rcParams['font.size'] = 11

max_iter = n_epochs - 1
epochs = range(1, n_epochs + 1)

fig, ax = plt.subplots(figsize=(6, 4))

ax.plot(epochs, train_F1_history, color='#2c3e50', linewidth=1.5,
        label='Training F1 (Last = %.4f)' % train_F1_history[max_iter])
ax.plot(epochs, val_F1_history, color='#c0392b', linewidth=1.5, linestyle='--',
        label='Validation F1 (Last = %.4f)' % val_F1_history[max_iter])

ax.set_title('Training and Validation F1 Score', fontsize=12, fontweight='bold', pad=10)
ax.set_xlabel('Epochs', fontsize=11)
ax.set_ylabel('F1 Score', fontsize=11)
ax.legend(fontsize=10, frameon=True, edgecolor='#cccccc', fancybox=False)

ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_linewidth(0.8)
ax.spines['bottom'].set_linewidth(0.8)
ax.tick_params(axis='both', labelsize=10, length=3)
ax.grid(False)

plt.tight_layout()
plt.savefig('f1_curve.pdf', dpi=300, bbox_inches='tight')
plt.show()

mpl.rcParams['font.family'] = 'serif'
mpl.rcParams['font.size'] = 11

max_iter = len(train_acc_history) - 1
epochs = range(1, len(train_acc_history) + 1)

fig, ax = plt.subplots(figsize=(6, 4))

ax.plot(epochs, train_acc_history, color='#2c3e50', linewidth=1.5,
        label='Training Accuracy (Last = %.4f)' % train_acc_history[max_iter])
ax.plot(epochs, val_acc_history, color='#c0392b', linewidth=1.5, linestyle='--',
        label='Validation Accuracy (Last = %.4f)' % val_acc_history[max_iter])

ax.set_title('Training and Validation Accuracy', fontsize=12, fontweight='bold', pad=10)
ax.set_xlabel('Epochs', fontsize=11)
ax.set_ylabel('Accuracy', fontsize=11)
ax.legend(fontsize=10, frameon=True, edgecolor='#cccccc', fancybox=False)

ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_linewidth(0.8)
ax.spines['bottom'].set_linewidth(0.8)
ax.tick_params(axis='both', labelsize=10, length=3)
ax.grid(False)

plt.tight_layout()
plt.savefig('accuracy_curve.pdf', dpi=300, bbox_inches='tight')
plt.show()

mpl.rcParams['font.family'] = 'serif'
mpl.rcParams['font.size'] = 11

max_iter = len(train_loss_history) - 1
epochs = range(1, len(train_loss_history) + 1)

fig, axes = plt.subplots(2, 2, figsize=(12, 8))

def style_ax(ax):
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_linewidth(0.8)
    ax.spines['bottom'].set_linewidth(0.8)
    ax.tick_params(axis='both', labelsize=10, length=3)
    ax.grid(False)

# --- (A) Loss ---
ax = axes[0, 0]
ax.plot(epochs, train_loss_history, color='#2c3e50', linewidth=1.5, label='Training Loss')
ax.plot(epochs, val_loss_history, color='#c0392b', linewidth=1.5, linestyle='--', label='Validation Loss')
ax.set_title('(A) Training and Validation Loss', fontsize=12, fontweight='bold', pad=10)
ax.set_xlabel('Epochs', fontsize=11)
ax.set_ylabel('Loss', fontsize=11)
ax.legend(fontsize=10, frameon=True, edgecolor='#cccccc', fancybox=False, loc='upper right')
style_ax(ax)

# --- (B) BAC ---
ax = axes[0, 1]
ax.plot(epochs, train_BAC_history, color='#2c3e50', linewidth=1.5,
        label='Training BAC (Last = %.4f)' % train_BAC_history[max_iter])
ax.plot(epochs, val_BAC_history, color='#c0392b', linewidth=1.5, linestyle='--',
        label='Validation BAC (Last = %.4f)' % val_BAC_history[max_iter])
ax.set_title('(B) Training and Validation BAC', fontsize=12, fontweight='bold', pad=10)
ax.set_xlabel('Epochs', fontsize=11)
ax.set_ylabel('BAC Value', fontsize=11)
ax.legend(fontsize=10, frameon=True, edgecolor='#cccccc', fancybox=False, loc='upper left')
style_ax(ax)

# --- (C) F1 ---
ax = axes[1, 0]
ax.plot(epochs, train_F1_history, color='#2c3e50', linewidth=1.5,
        label='Training F1 (Last = %.4f)' % train_F1_history[max_iter])
ax.plot(epochs, val_F1_history, color='#c0392b', linewidth=1.5, linestyle='--',
        label='Validation F1 (Last = %.4f)' % val_F1_history[max_iter])
ax.set_title('(C) Training and Validation F1 Score', fontsize=12, fontweight='bold', pad=10)
ax.set_xlabel('Epochs', fontsize=11)
ax.set_ylabel('F1 Score', fontsize=11)
ax.legend(fontsize=10, frameon=True, edgecolor='#cccccc', fancybox=False, loc='lower right')
style_ax(ax)

# --- (D) Accuracy ---
ax = axes[1, 1]
ax.plot(epochs, train_acc_history, color='#2c3e50', linewidth=1.5,
        label='Training Accuracy (Last = %.4f)' % train_acc_history[max_iter])
ax.plot(epochs, val_acc_history, color='#c0392b', linewidth=1.5, linestyle='--',
        label='Validation Accuracy (Last = %.4f)' % val_acc_history[max_iter])
ax.set_title('(D) Training and Validation Accuracy', fontsize=12, fontweight='bold', pad=10)
ax.set_xlabel('Epochs', fontsize=11)
ax.set_ylabel('Accuracy', fontsize=11)
ax.legend(fontsize=10, frameon=True, edgecolor='#cccccc', fancybox=False, loc='lower right')
style_ax(ax)

plt.tight_layout(pad=3.0)
plt.savefig('training_curves.pdf', dpi=300, bbox_inches='tight')
plt.show()

model.eval()
logits = model.forward()[category]
preds = logits[test_idx].argmax(dim=1).cpu().numpy()
true_labels = labels[test_idx].cpu().numpy()
probs = logits[test_idx].softmax(dim=1).cpu().detach().numpy()

test_loss = F.cross_entropy(logits[test_idx], labels[test_idx])
test_acc = (preds == true_labels).mean()
test_f1 = calculate_f1_score(logits[test_idx], labels[test_idx])
test_balanced_acc = calculate_balanced_accuracy(logits[test_idx], labels[test_idx])

test_precision = precision_score(true_labels, preds, average='weighted')
test_recall = recall_score(true_labels, preds, average='weighted')

if logits.shape[1] > 2:
    test_auc = roc_auc_score(true_labels, probs, multi_class='ovr', average='weighted')
else:
    test_auc = roc_auc_score(true_labels, probs[:, 1])

print(
    "Test Acc: {:.5f} | Test loss: {:.5f} | Test BAC: {:.5f} | Test F1: {:.5f} | Precision: {:.5f} | Recall: {:.5f} | AUC: {:.5f}".format(
        test_acc, test_loss.item(), test_balanced_acc, test_f1, test_precision, test_recall, test_auc
    )
)
print()

def calculate_roc_curve(logits, labels):
    probabilities = th.softmax(logits, dim=1)[:, 1]
    probabilities = probabilities.cpu().detach().numpy()
    labels = labels.cpu().numpy()

    fpr, tpr, thresholds = roc_curve(labels, probabilities)
    roc_auc = auc(fpr, tpr)

    return fpr, tpr, roc_auc

mpl.rcParams['font.family'] = 'serif'
mpl.rcParams['font.size'] = 11

model.eval()
logits = model.forward()[category]
fpr, tpr, roc_auc = calculate_roc_curve(logits[test_idx], labels[test_idx])

fig, ax = plt.subplots(figsize=(6, 4))

ax.plot(fpr, tpr, color='#c0392b', linewidth=2,
        label='ROC Curve (AUC = %.5f)' % roc_auc,
        zorder=2)
ax.plot([0, 1], [0, 1], color='#2c3e50', linewidth=1, linestyle='--',
        label='Random Classifier', zorder=1)

# Marker visibile al punto di partenza
ax.plot(fpr[0], tpr[0], 'o', color='#c0392b', markersize=5, zorder=3)

ax.set_xlim([-0.02, 1.0])
ax.set_ylim([0.0, 1.05])
ax.set_xlabel('False Positive Rate', fontsize=11)
ax.set_ylabel('True Positive Rate', fontsize=11)
ax.set_title('Receiver Operating Characteristic (ROC)', fontsize=12, fontweight='bold', pad=10)
ax.legend(fontsize=10, frameon=True, edgecolor='#cccccc', fancybox=False, loc='lower right')

ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_linewidth(0.8)
ax.spines['bottom'].set_linewidth(0.8)
ax.tick_params(axis='both', labelsize=10, length=3)
ax.grid(False)

plt.tight_layout()
plt.savefig('roc_curve.pdf', dpi=300, bbox_inches='tight')
plt.show()

model.eval()
logits = model.forward()[category]

predictions = th.argmax(logits[test_idx], dim=1).cpu().numpy()
predictions

# Classification Probabilities on test set

test_probabilities = th.softmax(logits[test_idx], dim=1)

np.set_printoptions(precision=5, suppress=True)
test_probabilities_np = test_probabilities.detach().numpy()
test_probabilities_rounded = np.around(test_probabilities_np, decimals=6)
test_probabilities_rounded

model.eval()
logits = model.forward()[category]

predictions = th.argmax(logits[test_idx], dim=1).cpu().numpy()

cm = confusion_matrix(labels[test_idx].cpu().numpy(), predictions)
cm

plt.figure(figsize=(8, 8))
ax = sns.heatmap(
    cm,
    annot=True,
    annot_kws={"color": "red", "size": 16, "weight": "bold"},
    fmt="d",
    cmap='Blues',
    xticklabels=["Not-CSP", "CSP"],
    yticklabels=["Not-CSP", "CSP"]
)
plt.ylabel('True Directors label', fontsize=14)
plt.xlabel('Predicted Directors label', fontsize=14)
plt.title('Confusion Matrix of Directors', fontsize=16, weight='bold')

bottom, top = ax.get_ylim()
ax.set_ylim(bottom + 0.5, top - 0.5)
plt.yticks(rotation=0, fontsize=12)
plt.xticks(rotation=45, fontsize=12)
plt.tight_layout()
plt.show()

model.eval()
with th.no_grad():
    h = model.embed_layer()
    embeddings = model(h)

embeddings

"""## T-SNE"""

embeddings_director = embeddings['director'].numpy()
embeddings_director

tsne = TSNE(n_components=2, perplexity=10, n_iter=1000, random_state=42)
tsne

embeddings_directors_2d = tsne.fit_transform(embeddings_director)
embeddings_directors_2d

num_labels = labels.numpy()

#### t-SNE Visualization ####


mpl.rcParams['font.family'] = 'serif'

color_map  = {1: '#08519c', 0: '#d94801', -1: '#bdbdbd'}
label_map  = {1: 'CSP', 0: 'Non-CSP', -1: 'Unknown'}
order      = [-1, 0, 1]

fig, ax = plt.subplots(figsize=(9, 7), facecolor='white')

for label in order:
    color = color_map[label]
    mask  = labels == label
    ax.scatter(
        embeddings_directors_2d[mask, 0],
        embeddings_directors_2d[mask, 1],
        c=color,
        label=label_map[label],
        s=20,
        alpha=0.7,
        edgecolor='none',
        linewidth=0,
        rasterized=True
    )

ax.axis('off')

legend = ax.legend(
    title="Labels",
    fontsize=15,
    title_fontsize=16,
    loc="center left",
    bbox_to_anchor=(1.01, 0.5),
    frameon=True,
    framealpha=0.9,
    edgecolor='#cccccc',
    fancybox=False,
    markerscale=2.5,
    handletextpad=0.8,
    borderpad=0.8
)
legend.get_title().set_fontweight('bold')
legend.get_title().set_fontfamily('serif')

plt.tight_layout()
plt.savefig('tsne_directors.pdf', dpi=300, bbox_inches='tight', format='pdf')
plt.show()

"""## UMAP"""

umap_reducer = umap.UMAP(n_neighbors=10, min_dist=0.1, n_components=2, random_state=42)
umap_reducer

embeddings_directors_2d_umap = umap_reducer.fit_transform(embeddings_director)
embeddings_directors_2d_umap

#### UMAP Visualization ####

import matplotlib.pyplot as plt
import matplotlib as mpl

mpl.rcParams['font.family'] = 'serif'

color_map  = {1: '#08519c', 0: '#d94801', -1: '#bdbdbd'}
label_map  = {1: 'CSP', 0: 'Non-CSP', -1: 'Unknown'}
order      = [-1, 0, 1]

fig, ax = plt.subplots(figsize=(9, 7), facecolor='white')

for label in order:
    color = color_map[label]
    mask  = labels == label
    ax.scatter(
        embeddings_directors_2d_umap[mask, 0],
        embeddings_directors_2d_umap[mask, 1],
        c=color,
        label=label_map[label],
        s=20,
        alpha=0.7,
        edgecolor='none',
        linewidth=0,
        rasterized=True
    )

ax.axis('off')

legend = ax.legend(
    title="Labels",
    fontsize=15,
    title_fontsize=16,
    loc="center left",
    bbox_to_anchor=(1.01, 0.5),
    frameon=True,
    framealpha=0.9,
    edgecolor='#cccccc',
    fancybox=False,
    markerscale=2.5,
    handletextpad=0.8,
    borderpad=0.8
)
legend.get_title().set_fontweight('bold')
legend.get_title().set_fontfamily('serif')

plt.tight_layout()
plt.savefig('umap_directors.pdf', dpi=300, bbox_inches='tight', format='pdf')
plt.show()

"""## Prediction on Unlabelled Data (Complex GNN)"""

no_labelled_test_mask = no_labelled_test_mask.bool()
no_labelled_test_mask

model.eval()
with th.no_grad(): #Gradient calculation disabled
    test_logits = model()[category][no_labelled_test_mask] #Logit for test set
    test_probs = th.softmax(test_logits, dim=1) # Conversion from logit in probabilities
    test_predictions = test_probs.argmax(dim=1) #Predictions

#Number of predicted CPS and Not CSP in Unlabelled Test Set

abs_freq = th.bincount(test_predictions)
abs_freq

#Proportion of predicted CPS and Not CSP in Unlabelled Test Set

rel_freq = abs_freq.float() / len(test_predictions)
rel_freq

df_predict = pd.DataFrame(test_probs, columns=['NON_CSP_prob', 'CSP_prob'])
df_predict

df_pred = pd.concat([df_predict, df_idx_unlab], axis=1)
df_pred

#### Merging Prediction and directors names ####

merged_df = pd.merge(df_directors_keys, df_pred, left_on='dir_id_key', right_on='dir_id', how='inner')
merged_df = merged_df.drop(columns=['dir_id_y']).rename(columns={'dir_id_x': 'dir_id'})

merged_df.head(15)

#### Merging Previous Dataset with Companies ####

final_df = pd.merge(merged_df, df_c_keys, on='bvd_id', how='inner')
final_df = final_df.drop(columns=['kvk_id'])

final_df.head(15)

#### Column Order ####

column_order = ['bvd_id', 'bvd_id_key', 'dir_id', 'dir_id_key', 'new_dir_id', 'company_name', 'dir_name', 'CSP_prob', 'NON_CSP_prob']
final_df = final_df[column_order]

final_df.head(15)

#### Sorting by CSP Probabilities ####

final_df = final_df.sort_values(by='CSP_prob', ascending=False)

final_df.head(25)

#### Saving Dataset ####

#final_df.to_csv('final_df.csv', index=False)